# Generated by Django 6.0.7 on 2026-07-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_options_alter_articleseries_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='subtile',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='subtile',
            new_name='subtitle',
        ),
    ]
