# Generated by Django 6.0.7 on 2026-07-20 23:09

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_options_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to),
        ),
    ]
